import type { Metadata } from "next";
import { EB_Garamond, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "app/providers";
import type { ReactNode } from "react";

const notoSans = Noto_Sans({ subsets: ["cyrillic"], variable: "--font-sans" });
const ebGaramond = EB_Garamond({
  subsets: ["cyrillic"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" className={notoSans.variable}>
      <body className={`${ebGaramond.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
